version: '2'
networks:
  web:
    external:
      name: reverseproxy_web
  internal:

services:

  # The router api
  opentripplanner:
    image: opentransitmap/opentripplanner
    restart: always
    command: "--build /data/graphs/nicaragua --server --basePath /data --router nicaragua --insecure"
    volumes:
      - ./data/opentripplanner:/data
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=opentripplanner"
      - "traefik.frontend.rule=Host:api.rutas.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=8080"
    networks:
      - web
      - internal

  # The user interface
  webui:
    image: opentransitmap/otm-webui
    restart: always
    volumes:
      - ./data/webui:/opt/digitransit-ui/app
    expose:
      - "8080"
    ports:
      - "9000"
    environment:
      - "NODE_ENV=production"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=userinterface"
      - "traefik.frontend.rule=Host:new.rutas.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=8080"
    networks:
      - web
      - internal

  # The background map
  map:
    image: nginx
    restart: always
    volumes:
      - ./data/map:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=map.rutas.mapanica.net"
      - "traefik.frontend.rule=Host:map.rutas.mapanica.net"
      - "traefik.docker.network=reverseproxy_web"
      - "traefik.port=80"
    networks:
      - web
      - internal
