version: '3'

networks:
  web:
    driver: "bridge"

services:
  proxy:
    image: "traefik:1.7"
    command: "--logLevel=INFO"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/:/cert/"
      - "./conf/:/etc/traefik/:ro"
    labels:
      - "traefik.enable=false" # set to true to expose Monitoring & API
      - "traefik.backend=proxy"
      - "traefik.port=8080"
    networks:
      - "web"
