# accept self-signed SSL certs for backends
InsecureSkipVerify = true

defaultEntryPoints = ["http", "https"]

[acme]
email = "contacto@mapanica.net"
storage = "cert/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true

# Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
[acme.httpChallenge]
  # EntryPoint to use for the challenges.
  entryPoint = "http"

[entryPoints]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
watch = true
exposedbydefault = false
